import { createHash, randomUUID } from 'node:crypto';
import { createWhatsAppLedger, whatsAppError } from './whatsapp-ledger.js';
import { createWhatsAppCalendly } from './whatsapp-calendly.js';
import * as profiles from './whatsapp-store.js';
import { sendWhatsAppText, whatsappStatus, verifyWhatsAppPhoneNumber } from './whatsapp.js';
import { workspaceProjectIds } from '../customer-care/adapters.js';

const hash = value => createHash('sha256').update(value).digest('hex');
const clean = (value, max = 2000) => String(value ?? '').trim().slice(0, max);
const iso = millis => new Date(millis).toISOString();
const canon = text => String(text).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9@.+ ]/g, ' ').replace(/\s+/g, ' ').trim();
const yes = text => /^(ja|ja bitte|ja buchen|buchen|bitte buchen|bestatigen|bestatigt|ja bestatigen)$/.test(canon(text));
const emailIn = text => { const found = String(text).match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9.-]*[A-Z0-9])?\.[A-Z]{2,63}/gi) || []; return found.length === 1 && found[0].length <= 254 ? found[0].toLowerCase() : ''; };
export function normalizeWhatsAppPhone(value) { let n = String(value || '').replace(/[\s()/.\-]/g, ''); if (n.startsWith('+')) n = n.slice(1); else if (n.startsWith('00')) n = n.slice(2); else if (n.startsWith('0')) n = '49' + n.slice(1); return /^[1-9]\d{6,14}$/.test(n) ? n : ''; }
export function createWhatsAppCustomers({ listWorkspaces, listProjects }) {
  return async projectId => { const [workspaces, allProjects] = await Promise.all([listWorkspaces({ mode: 'kunde' }), listProjects()]); return workspaces.filter(w => workspaceProjectIds(w, allProjects).includes(projectId)).map(w => ({ id: w.id, projectId, name: w.customer?.name || w.title || '', email: w.customer?.email || '', phone: w.customer?.phone || '', mobile: w.customer?.mobile || '', externalId: w.customer?.id || '' })); };
}
function intents(text) { const t = canon(text); return { appointment: /\b(termin|beratungstermin|kalender|rueckruf|ruckruf|sprechen)\b/.test(t), claim: /\b(schaden|wasserschaden|unfall|brand|einbruch|gestohlen|hagel|sturm)\b/.test(t), advice: /\b(versicherungsschutz|versichert|deckung|abgedeckt|gedeckt|ausschluss|rendite|empfehlung|empfiehlst|steuer|rechtlich|anlage|lohnt)\b/.test(t), human: /\b(mensch|berater|beraterin|mitarbeiter|personlich|beschwerde)\b/.test(t) }; }
function labelSlot(startTime, timezone) { return new Intl.DateTimeFormat('de-DE', { timeZone: timezone, weekday: 'long', day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(startTime)) + ` (${timezone})`; }
function profileFingerprint(p) { return hash(JSON.stringify([p.projectId, p.phoneNumberId, p.calendlyEventTypeUri, p.timezone, p.task])); }

export function createWhatsAppEngine({ dataDir, getProject, getCustomers = async () => [], profileStore = profiles, calendly = createWhatsAppCalendly(), sendText = sendWhatsAppText, verifyPhone = verifyWhatsAppPhoneNumber, env = process.env, now = () => Date.now() } = {}) {
  if (typeof getProject !== 'function') throw whatsAppError('Projektprüfung fehlt.');
  const ledger = createWhatsAppLedger({ dataDir }), active = new Map(); let tickActive = null;
  async function project(projectId) { if (!/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,119}$/.test(projectId || '') || ['__proto__', 'constructor', 'prototype'].includes(projectId) || !await getProject(projectId)) throw whatsAppError('WhatsApp-Projekt nicht verfügbar.', 403); }
  async function resolve(input, simulate) { const p = await profileStore.resolveWhatsAppProfile({ profileId: simulate ? input.profileId : '', phoneNumberId: input.phoneNumberId }); if (!p || (!simulate && !p.enabled) || !p.projectId || (!simulate && p.phoneNumberId !== input.phoneNumberId)) throw whatsAppError('Keine eindeutige aktive Projektzuordnung für diese WhatsApp-Nummer.', 409); await project(p.projectId); return p; }
  async function fresh(p, simulate) { const current = await profileStore.getWhatsAppProfile(p.id); if (!current || (!simulate && !current.enabled) || profileFingerprint(current) !== profileFingerprint(p)) throw whatsAppError('Die Nummern- oder Projektzuordnung wurde geändert. Der Vorgang bleibt offen.', 409); await project(p.projectId); return current; }
  async function customerFor(p, sender) { const rows = await getCustomers(p.projectId); const matched = rows.filter(c => (!c.projectId || c.projectId === p.projectId) && [c.phone, c.mobile].some(v => normalizeWhatsAppPhone(v) === sender)); return matched.length === 1 ? { status: 'matched', customer: { id: clean(matched[0].id, 160), name: clean(matched[0].name, 160), email: emailIn(matched[0].email) } } : { status: matched.length ? 'ambiguous' : 'not-found' }; }
  function handoff(c, p, reason, text) { c.handoff ||= { id: randomUUID(), projectId: p.projectId, profileId: p.id, customerId: c.customerId || '', status: 'open', owner: p.handoffOwner || '', priority: 'normal', reasons: [], statements: [], createdAt: iso(now()) }; if (!c.handoff.reasons.includes(reason)) c.handoff.reasons.push(reason); if (reason.includes('claim')) c.handoff.priority = 'high'; c.handoff.statements.push({ text: clean(text, 1500), at: iso(now()) }); c.handoff.statements = c.handoff.statements.slice(-30); c.handoff.updatedAt = iso(now()); c.handoff.dueAt ||= iso(now() + (p.handoffSlaMinutes || 240) * 60000); }
  async function offerSlots(c, p) {
    if (!p.calendlyEventTypeUri) { handoff(c, p, 'appointment-configuration', 'Calendly-Ereignis fehlt.'); c.phase = 'handoff'; return `Ich habe deine Terminanfrage zur persönlichen Abstimmung aufgenommen.${p.appointmentUrl ? ` Hier ist auch der Buchungslink: ${p.appointmentUrl}` : ''}`; }
    try {
      const result = await calendly.availability(p.calendlyEventTypeUri); await fresh(p, c.simulate);
      c.slots = result.slots.slice(0, 3).map((slot, i) => ({ number: i + 1, startTime: slot.startTime })); c.slotsCheckedAt = result.checkedAt; c.phase = 'choose-slot';
      if (!c.slots.length) { handoff(c, p, 'appointment-no-slots', 'Keine verfügbaren Termine im geprüften Zeitraum.'); c.phase = 'handoff'; return `Im geprüften Zeitraum zeigt Calendly keine freien Termine. Ich habe eine persönliche Terminabstimmung vorgemerkt.${p.appointmentUrl ? ` ${p.appointmentUrl}` : ''}`; }
      return `Diese Termine sind laut Calendly aktuell frei:\n${c.slots.map(s => `${s.number}. ${labelSlot(s.startTime, p.timezone)}`).join('\n')}\nWelche Nummer passt? Die Buchung bestätigst du anschließend noch einmal.`;
    } catch { handoff(c, p, 'appointment-provider-unavailable', 'Verfügbarkeiten noch nicht verifiziert.'); c.phase = 'handoff'; return `Ich kann die freien Zeiten gerade nicht zuverlässig abrufen. Deine Anfrage bleibt zur persönlichen Abstimmung offen.${p.appointmentUrl ? ` Du kannst den Buchungslink nutzen: ${p.appointmentUrl}` : ''}`; }
  }
  async function beginAppointment(c, p) {
    if (c.bookingId) { const existing = (await ledger.read()).bookings[c.bookingId]; if (existing) { handoff(c, p, 'appointment-existing', 'Weitere Terminabstimmung bei vorhandener Buchung nur persönlich.'); return existing.status === 'confirmed' ? `Es besteht bereits ein bestätigter Termin: ${labelSlot(existing.startTime, p.timezone)}. Weitere Termine oder Änderungen stimmt die Beratung persönlich ab.` : 'Eine frühere Buchung wird noch geprüft. Die Beratung klärt diesen Vorgang zuerst; ich lege keinen weiteren Termin an.'; } }
    c.booking = null; c.selectedSlot = null; c.emailConfirmedAt = null; c.schedulingFingerprint = profileFingerprint(p);
    if (!c.name) { c.phase = 'name'; return 'Gerne. Unter welchem Vor- und Nachnamen soll ich den Termin vorbereiten?'; }
    c.phase = 'email'; const masked = c.knownEmail ? c.knownEmail[0] + '***@' + c.knownEmail.split('@')[1] : '';
    return masked ? `Für die Einladung ist ${masked} vorgemerkt. Bitte bestätige die vollständige E-Mail-Adresse oder nenne die gewünschte neue Adresse.` : 'Welche E-Mail-Adresse soll die Termineinladung erhalten? Bitte nenne sie vollständig.';
  }
  async function book(c, p, inbound) {
    if (!c.email || !c.emailConfirmedAt || !c.selectedSlot) throw whatsAppError('Bestätigte Buchungsangaben fehlen.');
    if (c.simulate) { c.phase = 'simulation-complete'; return `Simulation abgeschlossen: ${labelSlot(c.selectedSlot.startTime, p.timezone)} für ${c.email}. Es wurde kein Termin gebucht und keine Nachricht versendet.`; }
    const id = 'booking-' + hash([p.projectId, p.id, c.id, c.selectedSlot.startTime, c.email].join('|')).slice(0, 40);
    let booking = (await ledger.read()).bookings[id];
    if (!booking) {
      const input = { id, projectId: p.projectId, profileId: p.id, conversationId: c.id, eventTypeUri: p.calendlyEventTypeUri, startTime: c.selectedSlot.startTime, email: c.email, name: c.name, sender: c.sender, timezone: p.timezone, confirmedByMessageId: inbound.messageId, confirmedAt: iso(now()), status: 'prepared' };
      let prepared;
      try { prepared = await calendly.prepareBooking(input); } catch (error) { if (error.code === 'CALENDLY_SLOT_GONE') return offerSlots(c, p); handoff(c, p, 'appointment-details', 'Termin benötigt persönliche Klärung oder zusätzliche Pflichtangaben.'); c.phase = 'handoff'; return `Für diesen Termin sind noch Angaben oder Berechtigungen zu klären. Ich habe die Buchung nicht ausgeführt.${p.appointmentUrl ? ` Bitte nutze den Buchungslink: ${p.appointmentUrl}` : ' Die Beratung übernimmt die Abstimmung.'}`; }
      await fresh(p, false);
      const claim = await ledger.transaction(state => { if (state.bookings[id]) return { owned: false, booking: state.bookings[id] }; state.bookings[id] = { ...input, status: 'attempted', attemptedAt: iso(now()) }; return { owned: true, booking: state.bookings[id] }; }); booking = claim.booking;
      if (claim.owned) {
        try { const receipt = await calendly.createBooking(booking, prepared); booking = await ledger.transaction(state => { state.bookings[id].receipt = receipt; state.bookings[id].status = 'verifying'; return state.bookings[id]; }); }
        catch (error) { booking = await ledger.transaction(state => { state.bookings[id].status = error.code === 'CALENDLY_REJECTED' ? 'rejected' : 'uncertain'; state.bookings[id].message = 'Buchungsbestätigung fehlt. Kein weiterer Buchungsversuch ausgeführt.'; return state.bookings[id]; }); }
      }
    }
    c.bookingId = id;
    if (!['confirmed', 'rejected'].includes(booking.status)) {
      try { const result = await calendly.reconcileBooking(booking); if (result.status === 'confirmed' && result.verified === true) booking = await ledger.transaction(state => { state.bookings[id].status = 'confirmed'; state.bookings[id].confirmation = result; state.bookings[id].verifiedAt = iso(now()); return state.bookings[id]; }); }
      catch { /* Readback can be resumed; never repeat the POST. */ }
    }
    if (booking.status === 'confirmed') { c.phase = 'booked'; return `Dein Termin ist in Calendly bestätigt: ${labelSlot(booking.startTime, p.timezone)}. Die Einladung geht an ${booking.email}.`; }
    handoff(c, p, 'appointment-readback', 'Der Buchungsstatus benötigt eine persönliche Prüfung. Nicht erneut buchen.'); c.phase = 'booking-uncertain'; return 'Der Termin ist noch nicht eindeutig bestätigt. Ich habe die Prüfung an die Beratung übergeben und buche nicht noch einmal, damit kein doppelter Termin entsteht.';
  }
  async function respond(c, p, inbound) {
    const text = inbound.text, intent = intents(text);
    if (!c.customerCheckedAt) { let found; try { found = await customerFor(p, c.sender); } catch { found = { status: 'unavailable' }; } c.customerStatus = found.status; c.customerCheckedAt = iso(now()); if (found.customer) { c.customerId = found.customer.id; c.name = found.customer.name; c.knownEmail = found.customer.email; } }
    if (/^(stop|stopp|abmelden|keine nachrichten)$/i.test(text.trim())) { c.phase = 'stopped'; return 'Verstanden. Ich stoppe die automatische Unterhaltung. Ein bereits bestätigter Termin wird dadurch nicht storniert.'; }
    if (c.phase === 'stopped') return null;
    if (!['text', 'button', 'interactive'].includes(inbound.type || 'text')) { handoff(c, p, p.task === 'claim' ? 'claim-media-review' : 'media-review', text); return 'Deine Nachricht ist eingegangen. Den Anhang habe ich noch nicht inhaltlich ausgewertet; er benötigt eine persönliche Prüfung. Bitte beschreibe das Anliegen zusätzlich kurz als Text.'; }
    if (['name', 'email', 'choose-slot', 'confirm-booking'].includes(c.phase) && c.schedulingFingerprint !== profileFingerprint(p)) { c.slots = []; c.emailConfirmedAt = null; return 'Die Terminzuordnung wurde inzwischen geändert. Ich bereite die Anfrage deshalb neu zur Bestätigung vor. ' + await beginAppointment(c, p); }
    if (intent.advice || intent.human) { handoff(c, p, intent.advice ? 'specialist-advice' : 'human-request', text); if (!intent.appointment) { c.phase = 'handoff'; return `Die fachliche Prüfung übernimmt die Beratung. Ich habe dein Anliegen mit dem bisherigen Stand vorgemerkt. ${p.handoffText || 'Eine persönliche Rückmeldung folgt.'}`; } }
    if (p.task === 'claim' && c.phase === 'idle' && !intent.claim && !intent.appointment) { c.phase = 'claim-description'; c.claim = { description: '', status: 'collecting', createdAt: iso(now()) }; return 'Ich unterstütze bei der Schadenaufnahme für die persönliche Prüfung. Was ist passiert? Bitte beschreibe den Schaden kurz.'; }
    if (c.phase === 'claim-description') { c.claim.description = clean(text, 3000); handoff(c, p, 'claim-intake', text); c.phase = 'claim-date'; return 'Wann ist der Schaden passiert? Eine Deckung oder Einreichung ist damit noch nicht bestätigt.'; }
    if (intent.claim && !c.claim) { c.claim = { description: clean(text, 3000), status: 'collecting', createdAt: iso(now()) }; c.phase = 'claim-date'; handoff(c, p, 'claim-intake', text); return 'Ich nehme den Schaden für die persönliche Prüfung auf; das ist noch keine Deckungszusage oder Meldung beim Versicherer. Wann ist der Schaden passiert? Bei akuter Gefahr bitte direkt den Notruf wählen.'; }
    if (c.phase === 'claim-date') { c.claim.occurredAtStatement = clean(text, 1000); c.phase = 'claim-location'; return 'Wo ist der Schaden passiert, und was wurde beschädigt?'; }
    if (c.phase === 'claim-location') { c.claim.locationAndDamageStatement = clean(text, 2000); c.claim.status = 'ready-for-review'; handoff(c, p, 'claim-review', text); c.phase = 'handoff'; return 'Die Schadenangaben sind für die Beratung vorgemerkt. Eine Deckungsentscheidung oder Einreichung beim Versicherer ist nicht erfolgt. Möchtest du dazu einen Beratungstermin abstimmen?'; }
    if (c.phase === 'booking-uncertain' || c.phase === 'booked') {
      const booking = (await ledger.read()).bookings[c.bookingId];
      if (booking?.status === 'confirmed') { c.phase = 'booked'; return `Der bestehende Termin ist bestätigt: ${labelSlot(booking.startTime, p.timezone)}. Für Änderungen übernimmt die Beratung die Abstimmung; ich habe keinen zweiten Termin angelegt.`; }
      return 'Die bestehende Buchung wird noch geprüft. Bitte buche denselben Termin nicht erneut; die Beratung klärt den tatsächlichen Status.';
    }
    if (c.phase === 'name') { if (text.length < 3 || text.length > 160 || emailIn(text) || /https?:\/\//i.test(text)) return 'Bitte nenne deinen Vor- und Nachnamen für die Termineinladung.'; c.name = clean(text, 160); return beginAppointment(c, p); }
    if (c.phase === 'email') { const email = emailIn(text); if (!email) return 'Bitte bestätige die vollständige E-Mail-Adresse für die Termineinladung. Ein einfaches „Ja“ reicht dafür noch nicht.'; c.email = email; c.emailConfirmedAt = iso(now()); c.emailConfirmationMessageId = inbound.messageId; return offerSlots(c, p); }
    if (c.phase === 'choose-slot') { const normalized = canon(text); if (/\b(andere|spater|nicht passend)\b/.test(normalized)) { handoff(c, p, 'appointment-alternative', text); c.phase = 'handoff'; return `Ich habe deinen Wunsch nach anderen Zeiten für die persönliche Abstimmung aufgenommen.${p.appointmentUrl ? ` Weitere Termine findest du hier: ${p.appointmentUrl}` : ''}`; } const number = /^(?:termin )?([123])$/.exec(normalized)?.[1] || ({ erste: '1', ersten: '1', zweite: '2', zweiten: '2', dritte: '3', dritten: '3' })[normalized.replace(/^(der|den) /, '')]; const selected = c.slots.find(s => s.number === Number(number)); if (!selected) return 'Bitte wähle einen der angebotenen Termine mit 1, 2 oder 3. Wenn keiner passt, schreibe „andere Termine“.'; c.selectedSlot = selected; c.phase = 'confirm-booking'; return `Soll ich verbindlich buchen: ${labelSlot(selected.startTime, p.timezone)}, Name ${c.name}, Einladung an ${c.email}? Antworte mit „Buchen“ oder „Nein“.`; }
    if (c.phase === 'confirm-booking') { if (yes(text)) return book(c, p, inbound); if (/\b(nein|andere|andern)\b/.test(canon(text))) { c.selectedSlot = null; return offerSlots(c, p); } return 'Noch ist nichts gebucht. Bitte bestätige den genannten Termin mit „Buchen“ oder lehne mit „Nein“ ab.'; }
    if (intent.appointment || (p.task === 'appointment' && c.phase === 'idle') || (c.phase === 'handoff' && yes(text) && c.claim)) return beginAppointment(c, p);
    const answer = (p.answers || []).find(a => canon(a.question) === canon(text) && a.source && a.verifiedAt);
    if (answer && !intents(answer.answer).advice && !/\b(gebucht|bestatigt|garant|sicher)/i.test(canon(answer.answer))) return clean(answer.answer, 1800);
    handoff(c, p, 'service-request', text); c.phase = 'handoff'; return `Ich habe dein Anliegen für die persönliche Bearbeitung aufgenommen. ${p.handoffText || 'Die Beratung übernimmt die fachliche Klärung.'}${p.calendlyEventTypeUri ? ' Wenn du möchtest, können wir einen Termin abstimmen.' : ''}`;
  }
  async function processInbound(id) {
    let state = await ledger.read(), original = state.inbound[id]; if (!original || ['completed', 'uncertain', 'ignored', 'failed'].includes(original.status)) return original;
    const p = await resolve(original, original.simulate), key = original.conversationId;
    if (active.has(key)) return { status: 'queued' };
    const task = (async () => {
      const acquired = await ledger.transaction(s => { const m = s.inbound[id], c = s.conversations[key]; if (!m || ['completed', 'uncertain', 'ignored', 'failed'].includes(m.status)) return null; if (c.processing && Date.parse(c.processing.expiresAt) > now()) { let alive = true; try { process.kill(c.processing.pid, 0); } catch (e) { if (e.code === 'ESRCH') alive = false; } if (alive) return null; } c.processing = { id, pid: process.pid, expiresAt: iso(now() + 600000) }; m.status = 'processing'; m.attempts = (m.attempts || 0) + 1; return { inbound: m, conversation: c }; });
      if (!acquired) return { status: 'queued' };
      const c = acquired.conversation, inbound = acquired.inbound;
      try {
        await fresh(p, inbound.simulate); let reply = inbound.reply || await respond(c, p, inbound); if (!inbound.reply && reply && !(c.messages || []).length && p.welcomeText) reply = clean(p.welcomeText, 1000) + '\n\n' + reply;
        await ledger.transaction(s => { const row = s.inbound[id]; if (s.conversations[key].processing?.id !== id) throw whatsAppError('Die Unterhaltung wird bereits weiterbearbeitet.', 409); c.lastInboundAt = s.conversations[key].lastInboundAt; if (!(c.messages || []).some(m => m.messageId === inbound.messageId)) c.messages = [...(c.messages || []), { role: 'user', text: inbound.text, messageId: inbound.messageId, at: inbound.receivedAt }, ...(reply ? [{ role: 'assistant', text: reply, at: iso(now()) }] : [])].slice(-40); c.updatedAt = iso(now()); s.conversations[key] = c; row.reply = reply; row.status = reply ? 'ready-to-send' : 'ignored'; });
        if (!reply) return { status: 'ignored', reply: '' };
        if (inbound.simulate) { await ledger.transaction(s => { s.inbound[id].status = 'completed'; s.inbound[id].delivery = 'simulation'; }); return { status: 'completed', simulated: true, reply, bookingCreated: false }; }
        await fresh(p, false);
        const delivery = await ledger.transaction(s => { if (s.outbound[id]) return { claimed: false, row: s.outbound[id] }; const at = s.conversations[key].lastInboundAt; if (now() - Date.parse(at) >= 86400000) { s.inbound[id].status = 'ignored'; return { expired: true }; } s.outbound[id] = { id, projectId: p.projectId, profileId: p.id, phoneNumberId: p.phoneNumberId, sender: inbound.sender, status: 'attempted', attemptedAt: iso(now()), lastInboundAt: at }; return { claimed: true, row: s.outbound[id] }; });
        if (delivery.expired) return { status: 'ignored', reason: 'service-window-expired' };
        if (!delivery.claimed) { await ledger.transaction(s => { if (['attempted', 'uncertain'].includes(s.outbound[id].status)) { s.outbound[id].status = 'uncertain'; s.inbound[id].status = 'uncertain'; handoff(s.conversations[key], p, 'delivery-readback', 'Früherer Versandversuch ohne eindeutigen Beleg; kein erneuter Versand.'); } else s.inbound[id].status = 'completed'; }); return { status: delivery.row.status, duplicate: true, reply: '' }; }
        try {
          const result = await sendText({ to: inbound.sender, text: reply, phoneNumberId: p.phoneNumberId, lastInboundAt: delivery.row.lastInboundAt, replyToMessageId: inbound.messageId });
          const providerMessageId = result.messages?.[0]?.id; if (!providerMessageId) throw new Error('no-receipt');
          await ledger.transaction(s => { s.outbound[id].status = 'accepted'; s.outbound[id].providerMessageId = providerMessageId; s.outbound[id].acceptedAt = iso(now()); s.inbound[id].status = 'completed'; });
          return { status: 'accepted', reply, providerMessageId };
        } catch { await ledger.transaction(s => { s.outbound[id].status = 'uncertain'; s.inbound[id].status = 'uncertain'; handoff(s.conversations[key], p, 'delivery-readback', 'Antwortversand ist ungeklärt; keine blinde Wiederholung.'); }); return { status: 'uncertain', reply: '', message: 'Versand noch nicht bestätigt; nicht erneut gesendet.' }; }
      } catch { await ledger.transaction(s => { if (s.inbound[id].status === 'processing') { s.inbound[id].status = s.inbound[id].attempts >= 3 ? 'failed' : 'queued'; if (s.inbound[id].status === 'failed') handoff(s.conversations[key], p, 'technical-review', 'Die gespeicherte Nachricht benötigt nach drei erfolglosen Verarbeitungsversuchen eine persönliche Prüfung.'); } }).catch(() => {}); return { status: 'queued', message: 'Vorgang bleibt zur gezielten Wiederaufnahme gespeichert.' }; }
      finally { await ledger.transaction(s => { if (s.conversations[key]?.processing?.id === id) delete s.conversations[key].processing; }).catch(() => {}); }
    })(); active.set(key, task); try { return await task; } finally { active.delete(key); }
  }
  async function receive(input, { simulate = input?.simulate === true, processMessage = true } = {}) {
    if (!simulate && input.verified !== true) throw whatsAppError('Nachricht benötigt einen geprüften Provider-Webhook.', 403);
    const p = await resolve(input, simulate), sender = normalizeWhatsAppPhone(input.sender), text = clean(input.text || input.message, 6000), messageId = clean(input.id || input.messageId, 250) || (simulate ? randomUUID() : '');
    if (!sender || !text || !messageId) throw whatsAppError('Absender, Text oder eindeutige Nachrichten-ID fehlen.');
    const timestamp = simulate ? now() : Number(input.timestamp) * 1000;
    if (!Number.isFinite(timestamp) || timestamp <= 0 || timestamp > now() + 60000) throw whatsAppError('Der Nachrichtenzeitpunkt ist nicht belegt.');
    const conversationId = hash([p.projectId, p.id, sender, simulate ? 'simulation' : 'live'].join('|')), id = hash([p.phoneNumberId, messageId, simulate ? 'simulation' : 'live'].join('|'));
    const previous = await ledger.transaction(s => { if (s.inbound[id]) { if (s.inbound[id].projectId !== p.projectId || s.inbound[id].profileId !== p.id) throw whatsAppError('Nachrichten-ID gehört zu einer früheren Nummernzuordnung.', 409); return s.inbound[id]; } s.conversations[conversationId] ||= { id: conversationId, projectId: p.projectId, profileId: p.id, sender, simulate, phase: 'idle', messages: [], createdAt: iso(now()) }; const c = s.conversations[conversationId]; c.lastInboundAt = iso(Math.max(Date.parse(c.lastInboundAt) || 0, timestamp)); s.inbound[id] = { id, messageId, conversationId, profileId: p.id, projectId: p.projectId, phoneNumberId: p.phoneNumberId, sender, text, type: clean(input.type, 30) || 'text', ...(input.media?.id ? { media: { id: clean(input.media.id, 200), mimeType: clean(input.media.mimeType, 120) } } : {}), simulate, timestamp: String(timestamp / 1000), receivedAt: iso(now()), status: now() - timestamp >= 86400000 ? 'ignored' : 'queued', attempts: 0 }; return null; });
    if (previous && ['completed', 'uncertain', 'ignored', 'failed'].includes(previous.status)) return { duplicate: true, status: previous.status, reply: '' };
    return processMessage ? processInbound(id) : { status: 'queued', durable: true, id };
  }
  async function runTick() {
    const state = await ledger.read();
    if (Object.keys(state.statusReceipts || {}).length) await acceptStatuses([], { verified: true });
    const results = []; for (const row of Object.values(state.inbound).filter(r => ['queued', 'processing', 'ready-to-send'].includes(r.status)).sort((a, b) => a.receivedAt.localeCompare(b.receivedAt)).slice(0, 20)) { try { results.push(await processInbound(row.id)); } catch { results.push({ status: 'waiting-configuration' }); } }
    for (const booking of Object.values(state.bookings).filter(b => ['attempted', 'verifying', 'uncertain'].includes(b.status) && (!b.nextCheckAt || Date.parse(b.nextCheckAt) <= now())).slice(0, 3)) { try { const claimed = await ledger.transaction(s => { const b = s.bookings[booking.id]; if (!['attempted', 'verifying', 'uncertain'].includes(b.status) || Date.parse(b.nextCheckAt) > now()) return false; b.readbackAttempts = (b.readbackAttempts || 0) + 1; b.nextCheckAt = iso(now() + Math.min(600000, 60000 * b.readbackAttempts)); return true; }); if (!claimed) continue; await project(booking.projectId); const result = await calendly.reconcileBooking(booking); if (result.verified && result.status === 'confirmed') await ledger.transaction(s => { s.bookings[booking.id].status = 'confirmed'; s.bookings[booking.id].confirmation = result; s.bookings[booking.id].verifiedAt = iso(now()); }); } catch {} }
    return { processed: results.length };
  }
  function tick() { if (tickActive) return tickActive; tickActive = runTick().finally(() => { tickActive = null; }); return tickActive; }
  async function acceptStatuses(rows, { verified = false } = {}) { if (!verified) throw whatsAppError('Status benötigt einen geprüften Meta-Webhook.', 403); return ledger.transaction(s => { s.statusReceipts ||= {}; let matched = 0; for (const row of rows) { if (!['sent', 'delivered', 'read', 'failed'].includes(row.status) || !row.id || !row.phoneNumberId || !normalizeWhatsAppPhone(row.recipient)) continue; const key = hash([row.phoneNumberId, row.id, row.status].join('|')); s.statusReceipts[key] = { id: clean(row.id, 250), phoneNumberId: clean(row.phoneNumberId, 100), recipient: normalizeWhatsAppPhone(row.recipient), status: row.status, timestamp: clean(row.timestamp, 30), receivedAt: iso(now()) }; } for (const [key, receipt] of Object.entries(s.statusReceipts)) { const outbound = Object.values(s.outbound).find(o => o.providerMessageId === receipt.id && o.phoneNumberId === receipt.phoneNumberId && o.sender === receipt.recipient); if (!outbound) continue; const order = { attempted: 0, uncertain: 0, accepted: 1, sent: 2, failed: 2, delivered: 3, read: 4 }; if ((order[receipt.status] || 0) >= (order[outbound.status] || 0)) { outbound.status = receipt.status; outbound.statusAt = iso(Number(receipt.timestamp) * 1000 || now()); matched++; } delete s.statusReceipts[key]; } return { matched, durable: true }; }); }
  async function listConversations({ projectId, simulate = false } = {}) { await project(projectId); const s = await ledger.read(); return Object.values(s.conversations).filter(c => c.projectId === projectId && c.simulate === simulate).sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0, 100).map(c => ({ ...c, processing: undefined, booking: c.bookingId ? s.bookings[c.bookingId] : null, deliveries: Object.values(s.outbound).filter(o => s.inbound[o.id]?.conversationId === c.id).slice(-5) })); }
  async function getBooking(projectId, id) { await project(projectId); const row = (await ledger.read()).bookings[id]; if (!row || row.projectId !== projectId) throw whatsAppError('Buchung nicht gefunden.', 404); return row; }
  async function verifyProfile(profileId) { const p = await profileStore.getWhatsAppProfile(profileId); if (!p) throw whatsAppError('Profil fehlt.', 404); await project(p.projectId); const phone = await verifyPhone(p.phoneNumberId), events = p.calendlyEventTypeUri ? await calendly.availability(p.calendlyEventTypeUri) : null; const result = { phone, calendly: events ? { verified: true, eventType: events.eventType, checkedAt: events.checkedAt, freeSlots: events.slots.length, bookingVerified: false } : { verified: false } }; await ledger.transaction(s => { s.checks[p.id] = result; }); return result; }
  async function status() { const state = await ledger.read(), inbound = Object.values(state.inbound).filter(m => !m.simulate), outbound = Object.values(state.outbound), bookings = Object.values(state.bookings); return { meta: whatsappStatus(env), calendly: calendly.status(), checks: state.checks, evidence: { scope: 'historical-events-not-current-connectivity', verifiedInbound: inbound.length > 0, lastInboundAt: inbound.map(m => m.receivedAt).sort().at(-1) || null, sendAccepted: outbound.some(m => m.providerMessageId), deliveryVerified: outbound.some(m => ['delivered', 'read'].includes(m.status)), bookingVerified: bookings.some(b => b.status === 'confirmed' && b.confirmation?.verified === true) }, counts: { queued: inbound.filter(m => ['queued', 'processing'].includes(m.status)).length, uncertainDeliveries: outbound.filter(m => ['attempted', 'uncertain'].includes(m.status)).length, uncertainBookings: bookings.filter(b => ['attempted', 'verifying', 'uncertain'].includes(b.status)).length }, bookingPolicy: 'confirmed-email-and-explicit-booking-approval-with-provider-readback', hub: { automatedInbound: false, reason: 'Der vorhandene Hub liefert noch keinen belegten signierten Nachrichtenkanal.' } }; }
  async function saveProfile(id, input) { const old = id ? await profileStore.getWhatsAppProfile(id) : null; if (id && !old) throw whatsAppError('Profil nicht gefunden.', 404); await project(input.projectId || old?.projectId); const saved = await (id ? profileStore.updateWhatsAppProfile(id, input) : profileStore.createWhatsAppProfile(input)); await ledger.transaction(s => { delete s.checks[saved.id]; }); return saved; }
  async function removeProfile(id) { const old = await profileStore.getWhatsAppProfile(id); if (!old) throw whatsAppError('Profil nicht gefunden.', 404); if (old.projectId) await project(old.projectId); return { ok: await profileStore.deleteWhatsAppProfile(id) }; }
  async function updateHandoff(projectId, conversationId, input = {}) { await project(projectId); return ledger.transaction(s => { const c = s.conversations[conversationId]; if (!c || c.projectId !== projectId || !c.handoff) throw whatsAppError('Übergabe nicht gefunden.', 404); if (!['open', 'in-progress', 'resolved'].includes(input.status)) throw whatsAppError('Ungültiger Bearbeitungsstand.'); c.handoff.status = input.status; c.handoff.updatedAt = iso(now()); if (input.owner !== undefined) c.handoff.owner = clean(input.owner, 200); if (input.note) c.handoff.statements.push({ text: clean(input.note, 1500), at: iso(now()), type: 'internal' }); return c.handoff; }); }
  return { receive, enqueueVerified: input => receive(input, { simulate: false, processMessage: false }), tick, acceptStatuses, listConversations, getBooking, verifyProfile, status, listCalendlyEventTypes: calendly.listEventTypes, listProfiles: profileStore.listWhatsAppProfiles, saveProfile, removeProfile, updateHandoff };
}
