import crypto from 'node:crypto';
import {createCoachStore,clean,fail} from './store.js';
import {transcribeCoachAudio,coachTranscriptionStatus,MAX_COACH_AUDIO_BYTES} from './transcribe.js';
import {generateCoachImpulse,coachModelStatus} from './coaching.js';
import {workspaceProjectIds} from '../customer-care/adapters.js';
const stamp=()=>new Date().toISOString();
const key=value=>{const result=clean(value,120);if(!/^[a-zA-Z0-9_-]{8,120}$/.test(result))throw fail('Eine gültige eindeutige Auftrags-ID fehlt.');return result;};
export function createSalesCoachService(deps={}){
  const store=createCoachStore(deps.dataDir||process.env.DATA_DIR||'/data'),active=new Map();
  const initialized=store.mutate(data=>{for(const session of data.sessions)for(const clip of session.clips||[])if(['processing','coaching'].includes(clip.status)){clip.status=clip.segments?.length?'partial':'uncertain';clip.reason='Serverlauf unterbrochen. Kein automatischer Neustart; bereits entstandene Kosten sind möglich.';}return true;});
  async function scopeProject(scope){const projectId=clean(scope?.projectId,160);if(!projectId)throw fail('Bitte ein Projekt wählen.');const project=await deps.getProject?.(projectId);if(!project)throw fail('Projekt nicht verfügbar.',404);return project;}
  async function customer(project,workspaceId){if(!workspaceId)return null;const workspace=await deps.getWorkspace?.(workspaceId);if(!workspace||workspace.mode!=='kunde'||!workspaceProjectIds(workspace,[project]).includes(project.id))throw fail('Die Kundenakte gehört nicht zu diesem Projekt.',404);return workspace;}
  function find(data,scope,id){const session=data.sessions.find(row=>row.id===id&&row.projectId===scope.projectId);if(!session)throw fail('Gespräch nicht gefunden.',404);return session;}
  async function readSession(scope,id){await initialized;await scopeProject(scope);return find(await store.read(),scope,id);}
  const publicSession=row=>{const {createKey,...result}=structuredClone(row);result.clips=result.clips.map(({sha256,...clip})=>clip);return result;};
  async function context(projectId){const projects=await deps.listProjects?.()||[],project=projectId?await scopeProject({projectId}):null,workspaces=project?await deps.listWorkspaces?.({mode:'kunde'})||[]:[];return{projects:projects.map(p=>({id:p.id,name:p.name})),customers:workspaces.filter(w=>workspaceProjectIds(w,[project]).includes(project.id)).map(w=>({id:w.id,name:w.customer?.name||w.title})),transcription:coachTranscriptionStatus(deps.env),coaching:coachModelStatus(deps.env),limits:{maxAudioBytes:MAX_COACH_AUDIO_BYTES,maxClips:240},capture:{samePhoneCall:false,diarizationAcrossClips:false,liveMode:'bounded-clips',clipSeconds:45,serverAudioStored:false}};}
  async function create(scope,input={}){await initialized;const project=await scopeProject(scope),workspaceId=clean(input.workspaceId,160);await customer(project,workspaceId);const createKey=key(input.idempotencyKey);if(input.consent?.granted!==true)throw fail('Bitte die Zustimmung zur Aufnahme und Auswertung dokumentieren.');return store.mutate(data=>{const existing=data.sessions.find(row=>row.projectId===project.id&&row.createKey===createKey);if(existing)return publicSession(existing);const now=stamp(),session={id:crypto.randomUUID(),createKey,projectId:project.id,workspaceId,title:clean(input.title,240)||'Gespräch & Notizen',goal:clean(input.goal,1500),mode:['live','note','import'].includes(input.mode)?input.mode:'note',consent:{granted:true,grantedAt:now,method:clean(input.consent.method,200)||'Vor Aufnahme ausdrücklich bestätigt'},status:'active',notes:'',clips:[],speakers:[],createdAt:now,updatedAt:now,meetingId:null};data.sessions.push(session);return publicSession(session);});}
  async function list(scope){await initialized;await scopeProject(scope);return(await store.read()).sessions.filter(row=>row.projectId===scope.projectId).slice(-100).reverse().map(row=>({id:row.id,title:row.title,workspaceId:row.workspaceId,status:row.status,mode:row.mode,createdAt:row.createdAt,clipCount:row.clips.length}));}
  async function get(scope,id){return publicSession(await readSession(scope,id));}
  async function update(scope,id,input={}){await readSession(scope,id);if('status'in input&&!['active','paused','complete'].includes(input.status))throw fail('Ungültiger Gesprächsstatus.');if(input.status&&input.status!=='active')active.get(id)?.abort();return store.mutate(data=>{const session=find(data,scope,id);if('notes'in input)session.notes=clean(input.notes,20000);if('title'in input)session.title=clean(input.title,240)||session.title;if(input.status)session.status=input.status;if(input.speakers){if(!Array.isArray(input.speakers)||input.speakers.length>500)throw fail('Ungültige Sprecherzuordnung.');for(const patch of input.speakers){const speaker=session.speakers.find(row=>row.id===patch.id);if(!speaker)throw fail('Unbekannter Sprecher.');speaker.name=clean(patch.name,100);speaker.confirmed=Boolean(speaker.name);}}session.updatedAt=stamp();return publicSession(session);});}
  async function ingestAudio(scope,id,buffer,input={},externalSignal){const session=await readSession(scope,id),clipId=key(input.clipId);if(!Buffer.isBuffer(buffer)||!buffer.length||buffer.length>MAX_COACH_AUDIO_BYTES)throw fail('Bitte eine Audiodatei bis 20 MB verwenden.',413);const sha256=crypto.createHash('sha256').update(buffer).digest('hex');const prior=session.clips.find(row=>row.id===clipId||row.sha256===sha256);if(prior){if(prior.id===clipId&&prior.sha256!==sha256)throw fail('Diese Auftrags-ID gehört zu einer anderen Aufnahme.',409);return{session:publicSession(session),clipId:prior.id,duplicate:true};}if(session.status!=='active')throw fail('Das Gespräch ist pausiert oder abgeschlossen. Zum Fortsetzen ausdrücklich öffnen.',409);if(active.has(id))throw fail('Ein Aufnahmeabschnitt wird bereits verarbeitet. Bitte dessen Ergebnis abwarten.',409);if(session.clips.length>=240)throw fail('Für dieses Gespräch sind bereits 240 Abschnitte gespeichert.',409);externalSignal?.throwIfAborted();const controller=new AbortController();active.set(id,controller);const signal=externalSignal?AbortSignal.any([externalSignal,controller.signal]):controller.signal;
    let accepted=false;
    try{const reservation=await store.mutate(data=>{const current=find(data,scope,id);const duplicate=current.clips.find(row=>row.id===clipId||row.sha256===sha256);if(duplicate)return{duplicate:true,clipId:duplicate.id};if(current.status!=='active')throw fail('Das Gespräch wurde pausiert.',409);current.clips.push({id:clipId,sha256,number:current.clips.length+1,status:'processing',createdAt:stamp(),fileName:clean(input.fileName,120),mime:clean(input.mime,100),audioBytes:buffer.length,segments:[],coaching:null,coachStatus:input.coachEnabled?'pending':'disabled'});return{duplicate:false};});if(reservation.duplicate)return{session:await get(scope,id),...reservation};accepted=true;
      signal.throwIfAborted();const result=await(deps.transcribe||transcribeCoachAudio)(buffer,{mime:input.mime,fileName:input.fileName,signal});
      // Save the paid transcription before optional coaching, including a late disconnect.
      await store.mutate(data=>{const current=find(data,scope,id),clip=current.clips.find(row=>row.id===clipId);clip.segments=result.segments.map(row=>({...row,id:clipId+':'+row.id,speakerId:clipId+':'+row.speakerId}));clip.text=result.text;clip.provider=result.provider;clip.model=result.model;clip.durationSeconds=result.durationSeconds;clip.status=input.coachEnabled&&clip.segments.length?'coaching':'complete';clip.transcribedAt=stamp();for(const row of result.speakers)current.speakers.push({...row,id:clipId+':'+row.id,clipId,label:'Abschnitt '+clip.number+' · '+row.label});current.updatedAt=stamp();return true;});
      if(input.coachEnabled&&result.segments.length){signal.throwIfAborted();const current=await readSession(scope,id),segments=current.clips.flatMap(row=>row.segments);try{const coaching=await(deps.coach||generateCoachImpulse)({segments,goal:current.goal,notes:current.notes,signal});await store.mutate(data=>{const clip=find(data,scope,id).clips.find(row=>row.id===clipId);clip.coaching=coaching;clip.coachStatus='complete';clip.status='complete';return true;});}catch(error){await store.mutate(data=>{const clip=find(data,scope,id).clips.find(row=>row.id===clipId);clip.coachStatus='unavailable';clip.status='partial';clip.reason='Transkript gespeichert. Coach-Impuls nicht bestätigt; keine automatische Wiederholung.';return true;});}}
      else if(input.coachEnabled)await store.mutate(data=>{const clip=find(data,scope,id).clips.find(row=>row.id===clipId);clip.coachStatus='no-speech';return true;});
      return{session:await get(scope,id),clipId,duplicate:false};
    }catch(error){if(!accepted)throw error;await store.mutate(data=>{const clip=find(data,scope,id).clips.find(row=>row.id===clipId);clip.status=clip.segments?.length?'partial':'uncertain';clip.coachStatus=clip.coachStatus==='complete'?'complete':'unavailable';clip.reason=signal.aborted?'Verbindung oder Aufnahme unterbrochen. Kein automatischer Neuaufruf; Anbieter kann den begonnenen Aufruf berechnen.':'Verarbeitung nicht bestätigt. Keine automatische Wiederholung; Anbieterzugang oder Aufnahme prüfen.';return true;});return{session:await get(scope,id),clipId,duplicate:false};}
    finally{if(active.get(id)===controller)active.delete(id);}
  }
  async function saveMeeting(scope,id,input={}){const session=await readSession(scope,id),project=await scopeProject(scope);if(!session.workspaceId)throw fail('Bitte das Gespräch mit einer Kundenakte anlegen.');await customer(project,session.workspaceId);if(input.reviewConfirmed!==true)throw fail('Bitte Transkript und Sprecherzuordnung vor Ablage prüfen.');if(active.has(id))throw fail('Bitte die laufende Verarbeitung vor Ablage abwarten.',409);const names=new Map(session.speakers.map(row=>[row.id,row.name||row.label]));const transcript=session.clips.flatMap(clip=>clip.segments.map(segment=>`${names.get(segment.speakerId)||'Nicht zugeordnet'}: ${segment.text}`)).join('\n');if(!transcript&&!session.notes)throw fail('Es ist noch kein Transkript oder Notiztext vorhanden.');if(transcript.length>100000)throw fail('Das Gespräch ist für eine Kundenaktennotiz zu groß. Bitte als Text exportieren.',422);const data={source:'live-coach',externalId:session.id,title:session.title,occurredAt:session.createdAt,status:'review',consent:session.consent,durationSeconds:session.clips.reduce((total,row)=>total+(row.durationSeconds||0),0),transcript,internalSummary:session.notes,segments:session.clips.flatMap(row=>row.segments),speakers:session.speakers,coachSessionId:session.id};const result=session.meetingId?await deps.updateWorkspaceMeeting(session.workspaceId,session.meetingId,data):await deps.addWorkspaceMeeting(session.workspaceId,data);if(!result?.meeting?.id)throw fail('Die Ablage wurde nicht bestätigt.',502);await store.mutate(store=>{const row=find(store,scope,id);row.meetingId=result.meeting.id;row.savedAt=stamp();row.status='complete';return true;});return{session:await get(scope,id),meetingId:result.meeting.id,saved:true};}
  return{context,create,list,get,update,ingestAudio,saveMeeting};
}
