import net from 'node:net';
import {createHash} from 'node:crypto';
export const clean=(value,max=500)=>String(value??'').replace(/[\u0000-\u0008\u000b-\u001f\u007f]/g,'').trim().slice(0,max);
export const list=(value,max=12)=>[...new Set((Array.isArray(value)?value:[]).map(x=>clean(x,160)).filter(Boolean))].slice(0,max);
export function publicUrl(value){try{const u=new URL(value),host=u.hostname.toLowerCase();if(!['http:','https:'].includes(u.protocol)||u.username||u.password||net.isIP(host)||host.includes(':')||!host.includes('.')||/\.(local|localhost|internal|test|invalid)$/.test(host)||host==='localhost')return'';u.hash='';for(const key of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(key))u.searchParams.delete(key);return u.href;}catch{return'';}}
const norm=value=>clean(value,10000).normalize('NFKC').toLocaleLowerCase('de-DE').replace(/\s+/g,' ');
export const FIELDS=['company','region','industry','contactName','role','website','linkedInUrl','businessEmail','businessPhone'];
export function normalizeSources(rows,now=new Date().toISOString()){
 const seen=new Set();return(Array.isArray(rows)?rows:[]).slice(0,10).flatMap(row=>{const url=publicUrl(row.url);if(!url||seen.has(url))return[];seen.add(url);return[{id:'s_'+createHash('sha256').update(url+'\n'+clean(row.text,5000)).digest('hex').slice(0,16),url,title:clean(row.title,300),text:clean(row.text,5000),snippet:clean(row.snippet,1200),kind:row.kind==='page-read'?'page-read':'search-hint',retrievedAt:now,publishedAt:clean(row.publishedAt,80)}];});
}
export function normalizeLeadCandidates(rows,sources,mode='leads'){
 const byId=new Map(sources.map(s=>[s.id,s]));return(Array.isArray(rows)?rows:[]).slice(0,20).flatMap(row=>{
  const facts={};for(const key of FIELDS){const fact=row.facts?.[key],source=byId.get(fact?.sourceId),value=clean(fact?.value,300),quote=clean(fact?.quote,700);if(!source||source.kind!=='page-read'||!value||!quote||!norm(source.text).includes(norm(quote))||!norm(quote).includes(norm(value)))continue;if(['website','linkedInUrl'].includes(key)&&!publicUrl(value))continue;if(key==='linkedInUrl'&&!/^https:\/\/(?:[a-z]{2,3}\.)?(?:www\.)?linkedin\.com\/(?:in|company)\//i.test(value))continue;if(key==='businessEmail'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))continue;facts[key]={value,sourceId:source.id,quote};}
  if(!facts.company)return[];
  // A name elsewhere on a directory page does not establish employment.
  // Require the quoted association itself to name both company and person.
  if(facts.contactName&&!norm(facts.contactName.quote).includes(norm(facts.company.value))){delete facts.contactName;delete facts.role;delete facts.businessEmail;delete facts.businessPhone;}
  if(mode==='recruiting'&&!facts.contactName)return[];
  const missing=(mode==='recruiting'?['company','contactName','role','region','linkedInUrl']:['company','website','region','industry','contactName','role']).filter(k=>!facts[k]);
  return[{facts,missing,completeness:Math.round((1-missing.length/(mode==='recruiting'?5:6))*100),reviewStatus:'unreviewed',deliveryStatus:'draft'}];
 });
}
export function leadKey(lead){const f=lead.facts,person=f.contactName?.value||'';if(f.linkedInUrl?.value&&/\/in\//.test(f.linkedInUrl.value))return norm(f.linkedInUrl.value).replace(/\/$/,'');const company=f.website?.value?new URL(f.website.value).hostname.replace(/^www\./,''):norm(f.company?.value);return norm(company+'|'+person+'|'+(person?'':f.region?.value||''));}
export function searchPlan(campaign){const base=[...campaign.industries,...campaign.regions].join(' '),roles=campaign.roles.join(' OR '),q=campaign.mode==='recruiting'?`${roles} ${base} Team Beruf Profil`:`${base} Unternehmen ${roles}`;return{queries:[clean(q,400),clean(`${base} ${roles} ${campaign.mode==='recruiting'?'Team Karriere Ansprechpartner':'Geschäftsführung Kontakt Impressum'}`,400)],linkedInUrl:'https://www.linkedin.com/search/results/people/?keywords='+encodeURIComponent([roles,base].filter(Boolean).join(' ')),companySearchUrl:'https://www.linkedin.com/search/results/companies/?keywords='+encodeURIComponent(base)};}
export function makeDraft(campaign,lead){const f=lead.facts,name=f.contactName?.value,company=f.company.value;return`${name?'Guten Tag '+name:'Guten Tag an das Team von '+company},\n\n${name?'ich bin auf Ihr berufliches Profil bei '+company+' aufmerksam geworden.':'ich bin auf '+company+' aufmerksam geworden.'}${f.role?.value?' Ihr Aufgabenbereich „'+f.role.value+'“ ist für meine Anfrage relevant.':''}\n\n${campaign.offer||'Ich würde gerne einen möglichen Austausch mit Ihnen prüfen.'}\n\nWäre ein kurzes Gespräch dazu für Sie interessant?` ;}
export function toCsv(campaign){const cell=value=>'"'+(/^[\s]*[=+@-]/.test(String(value??''))?"'":'')+String(value??'').replace(/"/g,'""')+'"';const rows=[['Unternehmen','Region','Branche','Ansprechpartner','Rolle','Website','LinkedIn','Geschäftliche E-Mail','Geschäftliches Telefon','Vollständigkeit %','Prüfstatus','Versandstatus','Quellen','Abgerufen','Entwurf'],...campaign.leads.map(l=>[...FIELDS.map(k=>l.facts[k]?.value||''),l.completeness,l.reviewStatus,'Entwurf – kein Versand',...[...new Set(Object.values(l.facts).map(f=>f.sourceId))].reduce((out,id)=>{const s=campaign.sources.find(s=>s.id===id);if(s){out[0].push(s.url);out[1].push(s.retrievedAt);}return out;},[[],[]]).map(a=>[...new Set(a)].join(' | ')),l.draft])];return'\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n');}
