import {randomUUID,createHash} from 'node:crypto';
import {createProjectStore,operationalError as fail,operationalId} from '../operations/project-store.js';
import {clean,list,normalizeLeadCandidates,leadKey,searchPlan,makeDraft,toCsv} from './evidence.js';
import {collectProspectingSources,extractProspectingLeads,prospectingReadiness} from './research.js';
const now=()=>new Date().toISOString(),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),key=value=>{const v=clean(value,100);if(!/^[a-zA-Z0-9_-]{8,100}$/.test(v))throw fail('Eine eindeutige Auftragskennung fehlt.');return v;};
function fields(input,previous={}){const v={...previous,...input},result={name:clean(v.name,160),mode:v.mode||'leads',industries:list(v.industries),regions:list(v.regions),roles:list(v.roles),offer:clean(v.offer,2500),notes:clean(v.notes,3000)};if(!result.name||!['leads','recruiting'].includes(result.mode))throw fail('Name und Art der Kampagne fehlen.');if(!result.industries.length&&!result.roles.length)throw fail('Bitte mindestens eine Branche oder ein Stellen-/Entscheiderprofil angeben.');return result;}
const publicCampaign=row=>{const copy=structuredClone(row);delete copy.createKey;delete copy.createHash;copy.jobs=copy.jobs.map(({key,inputHash,...job})=>job);copy.plan=searchPlan(copy);return copy;};
const find=(data,id)=>{operationalId(id);const c=data.campaigns.find(x=>x.id===id);if(!c)throw fail('Kampagne nicht im gewählten Projekt gefunden.',404);return c;};
const isRunning=c=>c.jobs.some(j=>j.status==='running'&&Date.now()-Date.parse(j.startedAt)<240000);
function settleExpired(c){for(const j of c.jobs)if(j.status==='running'&&Date.now()-Date.parse(j.startedAt)>=240000){j.status='uncertain';j.reason='Der Lauf wurde unterbrochen. Keine automatische Wiederholung.';j.finishedAt=now();}}
export function createProspectingService({dataDir,getProject,listProjects=async()=>[],env=process.env,collect,search,read,extract=extractProspectingLeads}={}){
 const store=createProjectStore({dataDir,name:'prospecting',getProject,initial:()=>({campaigns:[]})});const project=scope=>operationalId(scope?.projectId);
 async function context(projectId){if(projectId&&!await getProject(projectId))throw fail('Projekt nicht verfügbar.',404);const projects=await listProjects();return{projects:projects.map(p=>({id:p.id,name:p.name})),readiness:prospectingReadiness(env),limits:{searchRequests:2,sourcePages:8,modelRequests:1,maxLeads:300},notice:'Öffentliche Quellen können veraltet sein. Vollständigkeit zeigt vorhandene Datenfelder, keine Eignung und keine Kaufabsicht.'};}
 async function get(scope,id){const c=find(await store.read(project(scope)),id);settleExpired(c);return publicCampaign(c);}
 async function listCampaigns(scope){return(await store.read(project(scope))).campaigns.map(c=>{settleExpired(c);return{id:c.id,name:c.name,mode:c.mode,leadCount:c.leads.length,updatedAt:c.updatedAt,status:c.jobs.at(-1)?.status||'draft'};});}
 async function create(scope,input){const payload=fields(input),createKey=key(input.idempotencyKey),createHash=hash(payload);return store.mutate(project(scope),d=>{const prior=d.campaigns.find(c=>c.createKey===createKey);if(prior){if(prior.createHash!==createHash)throw fail('Diese Auftragskennung gehört zu einer anderen Kampagne.',409);return publicCampaign(prior);}if(d.campaigns.length>=60)throw fail('Die Projektgrenze von 60 Kampagnen ist erreicht.');const c={id:randomUUID(),projectId:scope.projectId,...payload,createKey,createHash,revision:1,createdAt:now(),updatedAt:now(),sources:[],leads:[],jobs:[]};d.campaigns.push(c);return publicCampaign(c);});}
 async function update(scope,id,input){return store.mutate(project(scope),d=>{const c=find(d,id);settleExpired(c);if(isRunning(c))throw fail('Die Recherche läuft. Zielgruppe danach ändern.',409);if(Number(input.baseRevision)!==c.revision)throw fail('Die Kampagne wurde zwischenzeitlich geändert. Bitte neu laden.',409);Object.assign(c,fields(input,c),{revision:c.revision+1,updatedAt:now()});return publicCampaign(c);});}
 async function research(scope,id,input={},signal){signal=signal?AbortSignal.any([signal,AbortSignal.timeout(180000)]):AbortSignal.timeout(180000);const jobKey=key(input.idempotencyKey),pid=project(scope);const reservation=await store.mutate(pid,d=>{const c=find(d,id);settleExpired(c);const prior=c.jobs.find(j=>j.key===jobKey);if(prior)return{existing:true,campaign:publicCampaign(c)};if(isRunning(c))throw fail('Für diese Kampagne läuft bereits eine Recherche.',409);if(c.jobs.length>=100)throw fail('Die Grenze von 100 Recherchen dieser Kampagne ist erreicht.');const status=prospectingReadiness(env);if(!collect&&!search&&!status.search.ready)throw fail('Websuche nicht verbunden. Tavily-Zugang einrichten.',503);if(extract===extractProspectingLeads&&!status.extraction.ready)throw fail('Modell für die Quellenauswertung nicht verbunden.',503);const job={id:randomUUID(),key:jobKey,status:'running',startedAt:now(),phase:'search',sourceCount:0,added:0,baseRevision:c.revision,queries:searchPlan(c).queries,target:{mode:c.mode,industries:c.industries,regions:c.regions,roles:c.roles}};c.jobs.push(job);c.updatedAt=now();return{existing:false,campaign:structuredClone(c),jobId:job.id};});if(reservation.existing)return reservation.campaign;
  const jobId=reservation.jobId;let sources=[];const active=(c,job)=>{signal.throwIfAborted();if(job.status!=='running'||c.revision!==reservation.campaign.revision)throw fail('Die Recherchefassung wurde geändert. Spätes Ergebnis nicht übernommen.',409);};
  try{signal?.throwIfAborted();const collected=await(collect||collectProspectingSources)(reservation.campaign,{env,search,read,signal});sources=collected.sources;await store.mutate(pid,d=>{const c=find(d,id),job=c.jobs.find(j=>j.id===jobId);active(c,job);for(const s of sources){const at=c.sources.findIndex(x=>x.id===s.id);if(at<0)c.sources.push(s);else c.sources[at]=s;}Object.assign(job,{phase:'extract',sourceCount:sources.length,warnings:collected.warnings||[]});});signal?.throwIfAborted();if(!sources.length&&(collected.warnings||[]).length)throw fail('Keine Suchantwort bestätigt.',502);
   const result=sources.some(s=>s.kind==='page-read')?await extract({campaign:reservation.campaign,sources,signal},{env}):{leads:[],model:null};signal?.throwIfAborted();const candidates=normalizeLeadCandidates(result.leads,sources,reservation.campaign.mode);
   return await store.mutate(pid,d=>{const c=find(d,id),job=c.jobs.find(j=>j.id===jobId);active(c,job);let added=0,duplicates=0;for(const lead of candidates){const dedupeKey=leadKey(lead),existing=c.leads.find(l=>l.dedupeKey===dedupeKey);if(existing){duplicates++;for(const [field,fact] of Object.entries(lead.facts))if(!existing.facts[field])existing.facts[field]=fact;else if(existing.facts[field].value!==fact.value){existing.reviewStatus='unreviewed';existing.conflictingFields=[...new Set([...(existing.conflictingFields||[]),field])];}const recalculated=normalizeLeadCandidates([{facts:existing.facts}],c.sources,c.mode)[0];if(recalculated){existing.completeness=recalculated.completeness;existing.missing=recalculated.missing;}existing.lastSeenAt=now();existing.revision++;continue;}if(c.leads.length>=300)break;const duplicateCampaignIds=d.campaigns.filter(other=>other.id!==c.id&&other.leads.some(l=>l.dedupeKey===dedupeKey)).map(x=>x.id);c.leads.push({...lead,id:randomUUID(),dedupeKey,duplicateCampaignIds,draft:makeDraft(c,lead),notes:'',createdAt:now(),lastSeenAt:now(),revision:1});added++;}Object.assign(job,{status:'complete',phase:'complete',finishedAt:now(),added,duplicates,model:result.model,reason:added?'Quellen und Treffer gespeichert. Vor Ansprache prüfen.':'Keine neuen ausreichend belegten Treffer. Quellen und Lücken bleiben sichtbar.'});c.updatedAt=now();c.revision++;return publicCampaign(c);});
  }catch(error){return await store.mutate(pid,d=>{const c=find(d,id),job=c.jobs.find(j=>j.id===jobId);if(job.status!=='running')return publicCampaign(c);Object.assign(job,{status:sources.length?'partial':'uncertain',phase:'stopped',finishedAt:now(),reason:signal?.aborted?'Verbindung unterbrochen. Gespeicherte Quellen bleiben erhalten; keine automatische Wiederholung.':'Recherche konnte nicht vollständig bestätigt werden. Quellen und bereits gespeicherte Treffer bleiben erhalten; keine automatische Wiederholung.'});c.updatedAt=now();return publicCampaign(c);});}
 }
 async function updateLead(scope,id,leadId,input){return store.mutate(project(scope),d=>{const c=find(d,id),lead=c.leads.find(l=>l.id===operationalId(leadId));if(!lead)throw fail('Kontakt nicht in dieser Kampagne gefunden.',404);if(Number(input.baseRevision)!==lead.revision)throw fail('Der Entwurf wurde geändert. Bitte neu laden.',409);if(input.deliveryStatus&&input.deliveryStatus!=='draft')throw fail('Ohne bestätigte Versandschnittstelle kann kein Versand eingetragen werden.');if(input.reviewStatus!==undefined&&!['unreviewed','reviewed','excluded'].includes(input.reviewStatus))throw fail('Ungültiger Prüfstatus.');if(input.reviewStatus==='reviewed'&&input.reviewConfirmed!==true)throw fail('Bitte Quellen und berufliche Zuordnung ausdrücklich prüfen.');if(input.draft!==undefined)lead.draft=clean(input.draft,5000);if(input.notes!==undefined)lead.notes=clean(input.notes,3000);if(input.reviewStatus!==undefined){lead.reviewStatus=input.reviewStatus;if(input.reviewStatus==='reviewed')lead.reviewedAt=now();}lead.revision++;c.updatedAt=now();return publicCampaign(c);});}
 return{context,list:listCampaigns,get,create,update,research,updateLead,exportCsv:async(scope,id)=>toCsv(await get(scope,id))};
}
