export const TAX_SOURCES = Object.freeze([
  {id:'estg4', title:'EStG § 4 – Betriebsausgaben und Einschränkungen',url:'https://www.gesetze-im-internet.de/estg/__4.html'},
  {id:'estg6', title:'EStG § 6 – Bewertung und geringwertige Wirtschaftsgüter',url:'https://www.gesetze-im-internet.de/estg/__6.html'},
  {id:'estg7', title:'EStG § 7 – Abschreibung',url:'https://www.gesetze-im-internet.de/estg/__7.html'},
  {id:'estg10', title:'EStG § 10 – Sonderausgaben',url:'https://www.gesetze-im-internet.de/estg/__10.html'},
  {id:'estg33', title:'EStG § 33 – Außergewöhnliche Belastungen',url:'https://www.gesetze-im-internet.de/estg/__33.html'},
  {id:'estg35a', title:'EStG § 35a – Haushaltsnahe Leistungen',url:'https://www.gesetze-im-internet.de/estg/__35a.html'},
  {id:'euer',title:'BMF – Anlage EÜR 2025 und Anleitung',url:'https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Einkommensteuer/2025-08-29-anlage-EUER-2025.html'},
]);
const q=(id,group,label,question,documents,tip,categories=[],source='euer',personal=false)=>({id,group,label,question,documents,tip,categories,source,personal});
export const TAX_QUESTIONS=Object.freeze([
  q('activity','Grundlagen','Tätigkeiten & Rechtsform','Welche selbständigen Tätigkeiten, Betriebe und Beteiligungen gab es im Steuerjahr?','Gewerbeanmeldung, Gesellschaftsunterlagen, Vorjahresbescheid','Jeden Betrieb und jede Rechtsform getrennt erfassen.'),
  q('method','Grundlagen','Gewinnermittlung','Ist EÜR oder Bilanz festgelegt? Gab es einen Wechsel?','Letzter Abschluss, Angaben der Steuerberatung','Die Methode nicht aus der Unternehmensgröße allein ableiten.'),
  q('vat','Grundlagen','Umsatzsteuer','Welche Umsätze sind regulär besteuert, steuerfrei oder unter Kleinunternehmerregelung?','Umsatzsteuerstatus, Voranmeldungen','Verschiedene Tätigkeiten und Auslandsumsätze einzeln zuordnen.'),
  q('income','Vollständigkeit','Einnahmen & Provisionen','Sind Rechnungen, Provisionen, Stornos und Erstattungen vollständig erfasst?','Ausgangsrechnungen, Provisionsabrechnungen, Stornonachweise','Stornos und Rückzahlungen getrennt nachvollziehbar halten.'),
  q('accounts','Vollständigkeit','Konten & Zahlungsdienste','Sind alle Geschäftskonten, Kassen, Karten und Zahlungsdienste abgeglichen?','Kontoauszüge, Kassenbuch, Zahlungsdienstabrechnungen','Auch Kosten auf privaten Konten zur Prüfung vormerken.'),
  q('year-cutoff','Vollständigkeit','Jahreswechsel','Gab es Zahlungen, Rechnungen oder regelmäßig wiederkehrende Posten rund um den Jahreswechsel?','Rechnungsdatum, Leistungszeitraum und Zahlungsdatum','Zeitliche Zuordnung benötigt alle drei Angaben.'),
  q('equipment','Arbeitsalltag','Computer & Arbeitsmittel','Welche Geräte, Büromöbel oder sonstigen Arbeitsmittel wurden angeschafft?','Rechnung, Kaufdatum, betrieblicher Nutzungsanteil','Sofortabzug und Abschreibung anhand des einzelnen Gegenstands prüfen.',['arbeitsmittel'],'estg6'),
  q('assets','Arbeitsalltag','Anlagen & Abschreibungen','Sind vorhandene Anlagen, Verkäufe und Entnahmen vollständig aufgelistet?','Anlagenverzeichnis, Abschreibungsplan, Veräußerungsbelege','Altanlagen und Abgänge in die Jahresvorbereitung einbeziehen.',['arbeitsmittel'],'estg7'),
  q('software','Arbeitsalltag','Software & KI-Abos','Welche Software-, Cloud-, KI- und Hosting-Abos werden beruflich genutzt?','Rechnungen und Nutzungszweck','Auslandsanbieter für die Umsatzsteuerprüfung kennzeichnen.',['software']),
  q('phone','Arbeitsalltag','Telefon & Internet','Welche Telefon- und Internetkosten wurden beruflich genutzt?','Rechnungen, nachvollziehbare Nutzungsaufteilung','Privaten Anteil dokumentieren.',['telekommunikation'],'estg4'),
  q('office','Räume','Büro & Coworking','Gab es Büro-, Lager- oder Coworking-Kosten?','Miete, Nebenkosten, Vertrag','Gemischte Nutzung erläutern.',['buero'],'estg4'),
  q('homeoffice','Räume','Arbeit zu Hause','An welchen Tagen wurde zu Hause gearbeitet und gibt es ein separates Arbeitszimmer?','Tagesaufzeichnung, Raumnutzung und Arbeitsplatzsituation','Arbeitszimmer und Tagespauschale nicht doppelt ansetzen.',['buero'],'estg4'),
  q('car','Mobilität','Fahrzeug','Welche Fahrzeuge wurden privat und betrieblich genutzt?','Fahrtenaufzeichnung, Kauf/Leasing, laufende Kosten','Nutzungsanteil und Bewertungsmethode klären.',['fahrzeug'],'estg6'),
  q('travel','Mobilität','Dienstreisen','Welche geschäftlichen Reisen und auswärtigen Termine gab es?','Reisedaten, Anlass, Fahrten, Hotelbelege','Betrieblichen Anlass belegen.',['reise'],'estg4'),
  q('meals','Mobilität','Verpflegung unterwegs','Gibt es vollständige Reisezeiten und Angaben zu gestellten Mahlzeiten?','Abwesenheitszeiten, Ziel, Arbeitgeber-/Veranstalterleistungen','Pauschalen und Kürzungen je Reise prüfen.',['reise'],'estg4'),
  q('hospitality','Kunden & Vertrieb','Geschäftliche Bewirtung','Sind geschäftliche Bewirtungen mit Anlass und Teilnehmern dokumentiert?','Bewirtungsbeleg, Teilnehmer, Anlass, Zahlungsnachweis','Begrenzten Abzug berücksichtigen.',['bewirtung'],'estg4'),
  q('gifts','Kunden & Vertrieb','Geschenke','Welche Geschenke wurden an welche Empfänger gegeben?','Empfängerliste, Einzelwerte, Anlass','Jahreswerte je Empfänger prüfen.',['geschenk'],'estg4'),
  q('marketing','Kunden & Vertrieb','Werbung & Veranstaltungen','Gab es Anzeigen, Websitekosten, Messen oder Contentproduktion?','Rechnungen und Kampagnenzweck','Zuordnung zum Betrieb festhalten.',['marketing'],'estg4'),
  q('training','Wissen & Beratung','Weiterbildung','Welche Kurse, Fachliteratur oder beruflichen Coachings wurden bezahlt?','Rechnung, Inhalt, beruflicher Bezug','Beruflichen Zusammenhang dokumentieren.',['fortbildung'],'estg4'),
  q('advisers','Wissen & Beratung','Steuer-, Rechts- & Bankkosten','Welche Beratungs- und Geschäftskontokosten gab es?','Rechnungen und Gebührenabrechnungen','Private Beratungsanteile getrennt halten.',['bank-steuerberatung'],'estg4'),
  q('insurance','Absicherung','Betriebliche Versicherungen','Welche Policen sichern betriebliche Risiken ab?','Police und Jahresbeitrag','Private Vorsorge separat erfassen.',['versicherung'],'estg4'),
  q('staff','Team','Personal & Fremdleistungen','Gab es Mitarbeiter, Minijobs, freie Mitarbeit oder Subunternehmer?','Abrechnungen, Verträge, Rechnungen','Beschäftigungsart und Zahlungen vollständig erfassen.',['fremdleistung']),
  q('interest','Finanzierung','Zinsen & Finanzierung','Gab es betriebliche Kredite, Leasing oder Überentnahmen?','Zins-/Tilgungsplan, Vertragszweck, Entnahmen','Zins und Tilgung trennen; Abzugsbegrenzungen prüfen.',['bank-steuerberatung'],'estg4'),
  q('founding','Sonderfälle','Gründung & Investitionen','Gab es Gründungskosten oder geplante größere Investitionen?','Belege, Investitionsplan und Zeitpunkt','Abschreibungs- und Investitionsfragen vorab klären.',['arbeitsmittel'],'estg7'),
  q('international','Sonderfälle','Ausland & Reverse Charge','Gab es ausländische Kunden, Anbieter oder Betriebsstätten?','Rechnungen, Länder, Leistungsarten','Sonderprüfung für Umsatzsteuer und Zuordnung vorsehen.'),
  q('grants','Sonderfälle','Zuschüsse & Erstattungen','Wurden Förderungen, Schadenersatz oder Kostenerstattungen gezahlt?','Bescheid, Abrechnung, Zahlungseingang','Jeden Vorgang mit seinem Zweck erfassen.'),
  q('private-use','Sonderfälle','Private Nutzung & Entnahmen','Sind privat genutzte Leistungen und Entnahmen aufgezeichnet?','Nutzungsaufteilungen, Entnahmeliste','Private Anteile nicht als vollen betrieblichen Aufwand führen.',['privat'],'estg4'),
  q('pension','Persönlich','Altersvorsorge','Welche privaten und gesetzlichen Vorsorgebeiträge wurden gezahlt?','Jahresbescheinigungen und Erstattungen','Sonderausgaben getrennt von Betriebsausgaben prüfen.',[],'estg10',true),
  q('health','Persönlich','Kranken- & Pflegeversicherung','Liegen Beitragsbescheinigungen, Zuschüsse und Erstattungen vor?','Jahresbescheinigungen der Versicherer','Relevante Beitragsanteile anhand der Bescheinigung prüfen.',[],'estg10',true),
  q('children','Persönlich','Kinder & Betreuung','Gab es Kinderbetreuung, Schulgeld oder Änderungen bei Kindern?','Betreuungsverträge, Rechnungen, Zahlungsbelege','Voraussetzungen und Zuordnung je Kind klären.',[],'estg10',true),
  q('household','Persönlich','Haushalt & Handwerker','Gab es bezahlte haushaltsnahe Dienstleistungen oder Handwerkerarbeiten?','Rechnung mit Arbeitskosten, unbarer Zahlungsnachweis','Doppelerfassung und geförderte Maßnahmen prüfen.',[],'estg35a',true),
  q('medical','Persönlich','Krankheit, Pflege & Belastungen','Gab es besondere Krankheits-, Pflege- oder behinderungsbedingte Aufwendungen?','Bescheinigungen, Kosten und Erstattungen','Individuelle Voraussetzungen und Eigenbelastung prüfen.',[],'estg33',true),
  q('other','Abschluss','Weitere Besonderheiten','Gibt es Spenden, Kirchensteuer, weitere Einkünfte, Verluste oder noch ungeklärte Ausgaben?','Bescheinigungen und offene Fragen','Besonderheiten vollständig zur Einzelfallprüfung mitgeben.'),
]);
export const TAX_REVIEWED_AT='2026-09-16';
