import {tool} from 'ai';
import {z} from 'zod';
export function customerCareSkill({service,projectId='',landing,websiteService,calculatorReadiness}) {
  const project=projectId?{}:{projectId:z.string().min(1).max(100)};
  const scope=input=>({projectId:projectId||input.projectId,...(input.customerId?{customerId:input.customerId}:{}),...(input.month?{month:input.month}:{})});
  const schedule=z.object({type:z.enum(['once','annual','contract']),at:z.string().optional(),from:z.string().optional(),to:z.string().optional(),month:z.number().int().min(1).max(12).optional(),day:z.number().int().min(1).max(31).optional(),leadDays:z.number().int().min(0).max(365).optional()});
  const tools={
    getCustomerCare:tool({description:'Liest die echte Kundenbetreuung im gewählten Projekt: Kunden, Themen, Kampagnen, Vertragsfristen, Monatsliste, priorisierte Rückmeldungen und tatsächliche Versandbelege. Liefert keine Kundendaten aus anderen Projekten.',parameters:z.object({...project,customerId:z.string().optional(),month:z.string().regex(/^\d{4}-\d{2}$/).optional()}),execute:input=>service.getDashboard(scope(input))}),
    setCustomerCarePreferences:tool({description:'Speichert auf Nutzerauftrag persönliche Themen, Kontaktfreigabe und Ausnahmen für einen Kunden. E-Mail-Freigabe niemals aus einer bloß vorhandenen Adresse ableiten.',parameters:z.object({...project,customerId:z.string(),care:z.object({enabled:z.boolean().optional(),emailAuthorized:z.boolean().optional(),topics:z.array(z.string()).max(20).optional(),annualCheckupEnabled:z.boolean().nullable().optional(),optimizationEnabled:z.boolean().nullable().optional(),preferredMonth:z.number().min(1).max(12).nullable().optional()})}),execute:input=>service.updateCustomerCare(scope(input),input.care)}),
    createCustomerCareCampaign:tool({description:'Speichert eine konkrete E-Mail-Kampagne mit Text, Zielthemen, optional ausgewählten Kunden und Zeitregel im Projekt. enabled aktiviert automatischen Versand nach den gespeicherten Regeln. Nur den vom Nutzer beauftragten Empfängerkreis und Inhalt einstellen; keine verbindlichen Preis- oder Leistungsvorteile ohne Beleg erfinden. queued ist noch nicht versendet.',parameters:z.object({...project,name:z.string().min(1).max(160),subject:z.string().min(1).max(200),body:z.string().min(1).max(12000),topics:z.array(z.string()).max(20),recipientIds:z.array(z.string()).max(500).optional(),schedule,enabled:z.boolean()}),execute:input=>service.createCampaign(scope(input),input)}),
    setCustomerCareCampaignEnabled:tool({description:'Aktiviert oder pausiert eine vorhandene Kundenkampagne auf Nutzerauftrag im aktuellen Projekt.',parameters:z.object({...project,campaignId:z.string(),enabled:z.boolean()}),execute:input=>service.updateCampaign(scope(input),input.campaignId,{enabled:input.enabled})}),
    createCustomerCheckupWebsite:tool({description:'Erstellt den mobilen Jahres-Check-up als bearbeitbare Seite im Website Studio des Projekts. Veröffentlicht noch keine Website und verändert keine bestehende Domain.',parameters:z.object(project),execute:input=>landing({projectId:scope(input).projectId},websiteService)}),
    getCustomerCalculatorReadiness:tool({description:'Prüft welche Kundenrechner rechnen, welche Szenarien liefern und welche Vergleichsportale noch keinen echten Tarifzugang haben. Anbieterpreise sind nur mit einem aktuellen Originalangebot bestätigt.',parameters:z.object({}),execute:async()=>calculatorReadiness()})
  };
  return Object.fromEntries(Object.entries(tools).map(([name,value])=>[name,{...value,...(projectId?{projectId}:{}),iva:{skillId:'advice'}}]));
}
